/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.conversao;

/**
 *
 * @author Aluno
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    Double numero, distancia;
    int selecionado, selection;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jConvertido = new javax.swing.JTextField();
        jConverter = new javax.swing.JButton();
        jResetar = new javax.swing.JButton();
        jExit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um ...", "Quilômetro (km)", "Metro (m)", "Decímetro (dm)", "Centímetro (cm)", "Milímetro (mm)" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um ...", "Quilômetro (km)", "Metro (m)", "Decímetro (dm)", "Centímetro (cm)", "Milímetro (mm)" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Comprimento");
        jLabel1.setMaximumSize(new java.awt.Dimension(90, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(90, 16));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Quero converter: ");

        jNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDisplay(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Para:");

        jConvertido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConvertidoActionPerformed(evt);
            }
        });

        jConverter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jConverter.setText("Converter");
        jConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConverterActionPerformed(evt);
            }
        });

        jResetar.setText("Resetar");
        jResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetarActionPerformed(evt);
            }
        });

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jConverter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jResetar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jExit))
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jConverter)
                .addGap(18, 18, 18)
                .addComponent(jConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jResetar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jNumero.getAccessibleContext().setAccessibleName("jDisplay");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
              selecionado =jComboBox1.getSelectedIndex();
              //jNumero.setText(String.valueOf(selecionado));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void jResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetarActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedItem("Escolha um ...");
        jComboBox2.setSelectedItem("Escolha um ...");
        
        jNumero.setText(null);
        jConvertido.setText(null);
    }//GEN-LAST:event_jResetarActionPerformed

    private void jTextDisplay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDisplay
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextDisplay

    private void jConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConverterActionPerformed
        // TODO add your handling code here:
     numero  = Double.parseDouble(jNumero.getText());
     if(selecionado == 1){
         switch(selection){
             case 1:
                 distancia = numero*1;
                 jConvertido.setText(String.valueOf(distancia + " km").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 2:              
                 distancia = numero*1000;
                 jConvertido.setText(String.valueOf(distancia + " m").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 3:
                 distancia = numero*10000;
                 jConvertido.setText(String.valueOf(distancia + " dm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 4:
                 distancia = numero*100000;
                 jConvertido.setText(String.valueOf(distancia + " cm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 5:
                 distancia = numero*1000000;
                 jConvertido.setText(String.valueOf(distancia + " mm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
        }
     }else if(selecionado == 2){
             switch(selection){
             case 1:
                 distancia = numero/1000;
                 jConvertido.setText(String.valueOf(distancia + " km").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 2:              
                 distancia = numero*1;
                 jConvertido.setText(String.valueOf(distancia + " m").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 3:
                 distancia = numero*10;
                 jConvertido.setText(String.valueOf(distancia + " dm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 4:
                 distancia = numero*100;
                 jConvertido.setText(String.valueOf(distancia + " cm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 5:
                 distancia = numero*1000;
                 jConvertido.setText(String.valueOf(distancia + " mm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             }
        }else if(selecionado == 3){
             switch(selection){
             case 1:
                 distancia = numero/10000;
                 jConvertido.setText(String.valueOf(distancia + " km").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 2:              
                 distancia = numero/10;
                 jConvertido.setText(String.valueOf(distancia + " m").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 3:
                 distancia = numero*1;
                 jConvertido.setText(String.valueOf(distancia + " dm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 4:
                 distancia = numero*10;
                 jConvertido.setText(String.valueOf(distancia + " cm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 5:
                 distancia = numero*100;
                 jConvertido.setText(String.valueOf(distancia + " mm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break; 
                }
         }else if(selecionado == 4){
             switch(selection){
             case 1:
                 distancia = numero/100000;
                 jConvertido.setText(String.valueOf(distancia + " km").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 2:              
                 distancia = numero/100;
                 jConvertido.setText(String.valueOf(distancia + " m").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 3:
                 distancia = numero/10;
                 jConvertido.setText(String.valueOf(distancia + " dm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 4:
                 distancia = numero*1;
                 jConvertido.setText(String.valueOf(distancia + " cm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 5:
                 distancia = numero*10;
                 jConvertido.setText(String.valueOf(distancia + " mm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
                } 
                }else if(selecionado == 5){
             switch(selection){
             case 1:
                 distancia = numero/10000;
                 jConvertido.setText(String.valueOf(distancia + " km").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 2:              
                 distancia = numero/1000;
                 jConvertido.setText(String.valueOf(distancia + " m").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 3:
                 distancia = numero/100;
                 jConvertido.setText(String.valueOf(distancia + " dm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 4:
                 distancia = numero/10;
                 jConvertido.setText(String.valueOf(distancia + " cm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break;
             case 5:
                 distancia = numero*1;
                 jConvertido.setText(String.valueOf(distancia + " mm").replaceFirst("\\.0*$|(\\.\\d*?)0+$","$1"));
                 break; 
                 }     
     }
    }//GEN-LAST:event_jConverterActionPerformed
        
    private void jConvertidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConvertidoActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jConvertidoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
      
      selection = jComboBox2.getSelectedIndex();
      //jConvertido.setText(String.valueOf(selection));

    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JButton jConverter;
    private javax.swing.JTextField jConvertido;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jResetar;
    // End of variables declaration//GEN-END:variables
}
